server:
  port: 8003
logging:
  file:
    path: log
spring:
  redis:
    # 单机配置
    host: localhost
    port: 6379
#    password:
     # 哨兵配置
#    sentinel:
#      master: gct
#      nodes: 10.100.2.1:26379,10.100.2.2:26379,10.100.2.3:26379
  application.name: accesslog-processing-simple
  datasource:
    clickhouse:
      jdbc-url: jdbc:clickhouse://localhost:8123/default
      username: default
      password:
accesslog-processing:
  thread-count: 2
  kafka-bootstrap-servers: localhost:9092
  kafka-consumer-group-id: accesslog-group
  topic-name: accesslog
  nginx_access_table: gp_nginx_access
